# Fertilizer Recommendation

## Import Library

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Data Exploration

In [2]:
data = pd.read_csv("Fertilizer Prediction.csv")

In [ ]:
data.tail(5)

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26,52,38,Sandy,Maize,37,0,0,Urea
1,29,52,45,Loamy,Sugarcane,12,0,36,DAP
2,34,65,62,Black,Cotton,7,9,30,14-35-14
3,32,62,34,Red,Tobacco,22,0,20,28-28
4,28,54,46,Clayey,Paddy,35,0,0,Urea

In [89]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Temparature      99 non-null     int64
 1   Humidity         99 non-null     int64
 2   Moisture         99 non-null     int64
 3   Soil Type        99 non-null     object
 4   Crop Type        99 non-null     object
 5   Nitrogen         99 non-null     int64
 6   Potassium        99 non-null     int64
 7   Phosphorous      99 non-null     int64
 8   Fertilizer Name  99 non-null     object
dtypes: int64(6), object(3)
memory usage: 7.1+ KB

In [94]:
data['Soil Type'].unique()

array(['Sandy', 'Loamy', 'Black', 'Red', 'Clayey'], dtype=object)

In [96]:
data['Crop Type'].unique()

array(['Maize', 'Sugarcane', 'Cotton', 'Tobacco', 'Paddy', 'Barley',
       'Wheat', 'Millets', 'Oil seeds', 'Pulses', 'Ground Nuts'],
      dtype=object)

In [98]:
data['Fertilizer Name'].unique()

array(['Urea', 'DAP', '14-35-14', '28-28', '17-17-17', '20-20',
       '10-26-26'], dtype=object)

In [71]:
data[data['Crop Type'] == "Cotton"]

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
2,34,65,62,Black,Cotton,7,9,30,14-35-14
6,25,50,64,Red,Cotton,9,0,10,20-20
12,25,50,65,Loamy,Cotton,36,0,0,Urea
18,28,54,65,Black,Cotton,39,0,0,Urea
26,30,60,63,Red,Cotton,9,9,29,14-35-14
36,30,60,61,Loamy,Cotton,8,10,31,14-35-14
54,31,62,63,Red,Cotton,11,12,15,17-17-17
62,34,65,64,Black,Cotton,24,0,20,28-28
65,36,68,62,Red,Cotton,15,0,40,DAP
79,34,65,63,Red,Cotton,14,0,38,DAP
82,29,58,65,Black,Cotton,14,0,35,DAP
89,29,58,61,Loamy,Cotton,11,0,38,DAP

## Data Preparation

In [120]:
data = data.rename(columns={
                                'Soil Type' : 'Soil_Type',
                                'Crop Type' : 'Crop_Type',
                                'Fertilizer Name' : 'Fertilizer_Name'
})

In [124]:
data

,Temparature,Humidity,Moisture,Soil_Type,Crop_Type,Nitrogen,Potassium,Phosphorous,Fertilizer_Name
0,26,52,38,Sandy,Maize,37,0,0,Urea
1,29,52,45,Loamy,Sugarcane,12,0,36,DAP
2,34,65,62,Black,Cotton,7,9,30,14-35-14
3,32,62,34,Red,Tobacco,22,0,20,28-28
4,28,54,46,Clayey,Paddy,35,0,0,Urea
...,...,...,...,...,...,...,...,...,...
94,25,50,32,Clayey,Pulses,24,0,19,28-28
95,30,60,27,Red,Tobacco,4,17,17,10-26-26
96,38,72,51,Loamy,Wheat,39,0,0,Urea
97,36,60,43,Sandy,Millets,15,0,41,DAP
98,29,58,57,Black,Sugarcane,12,0,10,20-20